package wake

import (
	"context"
	"testing"
	"time"

	"github.com/nozomemein/schlaflos/internal/config"
	"github.com/nozomemein/schlaflos/internal/platform/macos/cmdrun"
)

const schedNone = "No scheduled events.\n"

const schedOneOffOnly = `Scheduled power events:
 [0]  wake at 09/14/2026 11:20:00 by 'com.apple.alarm.user-invisible-com.apple.calaccessd.alarmEngine.alarm.name'
 [1]  wake at 09/14/2026 15:58:44 by 'com.apple.alarm.user-invisible-com.apple.acmd.alarm'
`

const schedOurs = `Repeating power events:
  wakepoweron at 8:00AM every day
Scheduled power events:
 [0]  wake at 09/14/2026 11:20:00 by 'com.apple.alarm.user-invisible-com.apple.acmd.alarm'
`

const schedPair = `Repeating power events:
  wake at 12:30PM weekdays only
  shutdown at 0:05AM Sunday
`

const schedSomeDays = `Repeating power events:
  wakepoweron at 7:00AM Some days
`

const autoWakeXML = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>RepeatingPowerOn</key>
	<dict>
		<key>eventtype</key>
		<string>wakepoweron</string>
		<key>time</key>
		<integer>420</integer>
		<key>weekdays</key>
		<integer>63</integer>
	</dict>
	<key>WARNING</key>
	<string>Do not edit this file by hand. It must remain in sorted-by-date order.</string>
	<key>wake</key>
	<array>
		<dict>
			<key>UserVisible</key>
			<false/>
			<key>appPID</key>
			<integer>999</integer>
			<key>eventtype</key>
			<string>wake</string>
			<key>time</key>
			<date>2026-09-14T02:20:00Z</date>
		</dict>
	</array>
</dict>
</plist>
`

func TestParseSched(t *testing.T) {
	for _, in := range []string{schedNone, schedOneOffOnly, ""} {
		s, err := ParseSched([]byte(in))
		if err != nil || !s.Empty() {
			t.Fatalf("ParseSched(%q) = %v, %v", in, s, err)
		}
	}
	s, err := ParseSched([]byte(schedOurs))
	if err != nil {
		t.Fatal(err)
	}
	want := Schedule{On: &Event{Type: TypeWakeOrPowerOn, Minutes: 480, Days: EveryDay, DaysExact: true, DaysLabel: "every day"}}
	if !s.Equal(want) || s.Off != nil || s.String() != "wakeorpoweron MTWRFSU 08:00:00" {
		t.Fatalf("ParseSched(ours) = %+v (%s)", s.On, s)
	}
	s, err = ParseSched([]byte(schedPair))
	if err != nil {
		t.Fatal(err)
	}
	if s.On == nil || s.On.Type != TypeWake || s.On.Minutes != 12*60+30 || s.On.Days != Weekdays {
		t.Fatalf("pair on = %+v", s.On)
	}
	if s.Off == nil || s.Off.Type != TypeShutdown || s.Off.Minutes != 5 || s.Off.Days != Sunday {
		t.Fatalf("pair off = %+v", s.Off)
	}
	if s.String() != "wake MTWRF 12:30:00; shutdown U 00:05:00" {
		t.Fatalf("String = %q", s)
	}
	s, err = ParseSched([]byte(schedSomeDays))
	if err != nil {
		t.Fatal(err)
	}
	if s.On == nil || s.On.DaysExact || s.On.DaysLabel != "Some days" || s.Exact() {
		t.Fatalf("some days = %+v", s.On)
	}
	if _, err := ParseSched([]byte("Repeating power events:\n  wakepoweron at noon every day\n")); err == nil {
		t.Fatal("garbage line accepted")
	}
}

func TestTimeParsing(t *testing.T) {
	cases := map[string]int{
		"0:00AM": 0, "12:00PM": 12 * 60, "1:00PM": 13 * 60, "11:59PM": 23*60 + 59, "8:05AM": 8*60 + 5,
	}
	for in, want := range cases {
		s, err := ParseSched([]byte("Repeating power events:\n  wake at " + in + " every day\n"))
		if err != nil || s.On.Minutes != want {
			t.Fatalf("%s -> %v (%v), want %d", in, s.On, err, want)
		}
	}
}

func TestLabelsAndLetters(t *testing.T) {
	cases := []struct {
		mask    DayMask
		letters string
		label   string
	}{
		{EveryDay, "MTWRFSU", "every day"},
		{Weekdays, "MTWRF", "weekdays only"},
		{Weekends, "SU", "weekends only"},
		{Thursday, "R", "Thursday"},
		{Monday | Wednesday, "MW", "Some days"},
	}
	for _, tc := range cases {
		if tc.mask.Letters() != tc.letters || tc.mask.Label() != tc.label {
			t.Fatalf("mask %07b: %q %q", tc.mask, tc.mask.Letters(), tc.mask.Label())
		}
		if m, ok := maskFromLabel(tc.label); tc.label != "Some days" && (!ok || m != tc.mask) {
			t.Fatalf("maskFromLabel(%q) = %v %v", tc.label, m, ok)
		}
	}
	if MaskFromWeekdays([]time.Weekday{time.Sunday, time.Monday}) != Monday|Sunday {
		t.Fatal("MaskFromWeekdays wrong")
	}
}

func TestFromConfigAndEqual(t *testing.T) {
	w := config.Wake{Enabled: true, Days: []time.Weekday{time.Monday, time.Tuesday, time.Wednesday, time.Thursday, time.Friday, time.Saturday, time.Sunday}, Time: config.Clock{Hour: 8}, Action: config.WakeActionWakeOrPowerOn}
	desired := FromConfig(w)
	observed, _ := ParseSched([]byte(schedOurs))
	if !desired.Equal(observed) {
		t.Fatalf("desired %s != observed %s", desired, observed)
	}
	if FromConfig(config.Wake{}).Empty() != true {
		t.Fatal("disabled wake must produce an empty schedule")
	}
	// Inexact observation compares by label.
	someDays, _ := ParseSched([]byte(schedSomeDays))
	mw := Schedule{On: &Event{Type: TypeWakeOrPowerOn, Minutes: 420, Days: Monday | Wednesday, DaysExact: true}}
	if !someDays.Equal(mw) {
		t.Fatal("inexact schedule should compare equal by label")
	}
	if someDays.Equal(desired) {
		t.Fatal("different time compared equal")
	}
}

func TestParseAutoWakePlist(t *testing.T) {
	s, err := ParseAutoWakePlist([]byte(autoWakeXML))
	if err != nil {
		t.Fatal(err)
	}
	if s.On == nil || s.On.Type != TypeWakeOrPowerOn || s.On.Minutes != 420 || s.On.Days != Weekdays|Saturday || !s.On.DaysExact || s.Off != nil {
		t.Fatalf("plist schedule = %s", s)
	}
	if _, err := ParseAutoWakePlist([]byte("<plist><array/></plist>")); err == nil {
		t.Fatal("non-dict accepted")
	}
}

func TestCurrentRefinesSomeDaysFromPlist(t *testing.T) {
	fake := &cmdrun.Fake{Responses: map[string]cmdrun.Response{
		"/usr/bin/pmset -g sched": {Stdout: schedSomeDays},
		"/usr/bin/plutil -convert xml1 -o - /Library/Preferences/SystemConfiguration/com.apple.AutoWake.plist": {Stdout: autoWakeXML},
	}}
	s, err := Adapter{Runner: fake}.Current(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if !s.On.DaysExact || s.On.Days != Weekdays|Saturday {
		t.Fatalf("refinement failed: %+v", s.On)
	}
	// Without the plist the observation stays inexact but is not an error.
	fake = &cmdrun.Fake{Responses: map[string]cmdrun.Response{
		"/usr/bin/pmset -g sched": {Stdout: schedSomeDays},
	}}
	s, err = Adapter{Runner: fake}.Current(context.Background())
	if err != nil || s.On.DaysExact {
		t.Fatalf("fallback: %v %+v", err, s.On)
	}
	// An exact observation never touches plutil.
	fake = &cmdrun.Fake{Responses: map[string]cmdrun.Response{
		"/usr/bin/pmset -g sched": {Stdout: schedOurs},
	}}
	if _, err := (Adapter{Runner: fake}).Current(context.Background()); err != nil {
		t.Fatal(err)
	}
	if len(fake.Calls) != 1 {
		t.Fatalf("calls = %v", fake.CallLines())
	}
}

func TestApplyArgvAndVerification(t *testing.T) {
	current := schedNone
	fake := &cmdrun.Fake{Handler: func(c cmdrun.Call) (cmdrun.Response, bool) {
		switch c.String() {
		case "/usr/bin/pmset -g sched":
			return cmdrun.Response{Stdout: current}, true
		case "/usr/bin/pmset repeat wakeorpoweron MTWRFSU 08:00:00":
			current = schedOurs
			return cmdrun.Response{}, true
		case "/usr/bin/pmset repeat wake MTWRF 12:30:00 shutdown U 00:05:00":
			current = schedPair
			return cmdrun.Response{}, true
		case "/usr/bin/pmset repeat cancel":
			current = schedNone
			return cmdrun.Response{}, true
		}
		return cmdrun.Response{}, false
	}}
	a := Adapter{Runner: fake}
	ours := Schedule{On: &Event{Type: TypeWakeOrPowerOn, Minutes: 480, Days: EveryDay, DaysExact: true}}
	if err := a.Apply(context.Background(), ours); err != nil {
		t.Fatal(err)
	}
	pair := Schedule{
		On:  &Event{Type: TypeWake, Minutes: 12*60 + 30, Days: Weekdays, DaysExact: true},
		Off: &Event{Type: TypeShutdown, Minutes: 5, Days: Sunday, DaysExact: true},
	}
	if err := a.Apply(context.Background(), pair); err != nil {
		t.Fatal(err)
	}
	if err := a.Apply(context.Background(), Schedule{}); err != nil {
		t.Fatal(err)
	}
	want := []string{
		"/usr/bin/pmset repeat wakeorpoweron MTWRFSU 08:00:00",
		"/usr/bin/pmset -g sched",
		"/usr/bin/pmset repeat wake MTWRF 12:30:00 shutdown U 00:05:00",
		"/usr/bin/pmset -g sched",
		"/usr/bin/pmset repeat cancel",
		"/usr/bin/pmset -g sched",
	}
	got := fake.CallLines()
	if len(got) != len(want) {
		t.Fatalf("calls = %v", got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("call %d = %q, want %q", i, got[i], want[i])
		}
	}
	// A write that does not take effect is reported.
	stuck := &cmdrun.Fake{Responses: map[string]cmdrun.Response{
		"/usr/bin/pmset repeat wakeorpoweron MTWRFSU 08:00:00": {},
		"/usr/bin/pmset -g sched":                              {Stdout: schedNone},
	}}
	if err := (Adapter{Runner: stuck}).Apply(context.Background(), ours); err == nil {
		t.Fatal("unverified write accepted")
	}
	// Inexact schedules are never written.
	if err := a.Apply(context.Background(), Schedule{On: &Event{Type: TypeWake, DaysLabel: "Some days"}}); err == nil {
		t.Fatal("inexact schedule written")
	}
}
